openapi: 3.0.3
info:
  title: Openapi Common Error types
  description: 'Error types, that can be used across all applications'
  version: 1.0.2
  license:
    name: All rights reserved by multi-module-maven-release-plugin
paths: { }
components:
  schemas:
    Fault:
      description: Generic Fault.
      type: object
      required:
        - errors
      properties:
        errors:
          type: array
          items:
            $ref: "#/components/schemas/Error"
    Error:
      description: Generic Error.
      type: object
      required:
        - id
        - status
        - message
      properties:
        id:
          description: UUID for log analyses (to trace back calls to the JFA server), should be logged by the caller
          type: string
        status:
          description: The HTTP status code associated with this Error
          type: integer
          minimum: 100
          maximum: 999
        message:
          description: Non-translated exception message, meant for logging.
          type: string
        code:
          description: |
            Optional code, to further specify the cause.
            Possible values are to be defined per usage of the Fault.
          type: string
        transferId:
          description: The transferId received in the request.
          type: string
        correlationId:
          description: The correlationId received in the request.
          type: string
        translations:
          description: |
            Optional, map for translated messages, which can directly be used to show to the user (UI).
            Key is an ISO 2 locale eg. "de", "en", "fr", "it" etc.
          type: object
          additionalProperties:
            type: string
        messageKey:
          description: |
            Optional, a message key to translate the error on client side (together with 'params').
          type: string
        params:
          description: |
            Optional, generic map for cases, where additional informations are to be returned.
            Expected params are to defined per usage of the Fault.
          type: object
          additionalProperties:
            type: string
